# Generated by Django 5.2.8 on 2025-11-15 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='추첨일')),
                ('n1', models.IntegerField(blank=True, null=True)),
                ('n2', models.IntegerField(blank=True, null=True)),
                ('n3', models.IntegerField(blank=True, null=True)),
                ('n4', models.IntegerField(blank=True, null=True)),
                ('n5', models.IntegerField(blank=True, null=True)),
                ('n6', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 시간')),
                ('buyer_name', models.CharField(blank=True, max_length=50, verbose_name='구매자 이름')),
                ('is_auto', models.BooleanField(default=False, verbose_name='자동 여부')),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('n3', models.IntegerField()),
                ('n4', models.IntegerField()),
                ('n5', models.IntegerField()),
                ('n6', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto_app.lottoround', verbose_name='회차')),
            ],
        ),
    ]
